server:
  rootPath: /api/*
dateFormat: yyyy-MM-dd'T'HH:mmZ

logging:
  level: INFO
  loggers:
    com.ua.chat: DEBUG

swagger:
  resourcePackage: com.ua.chat.resources

database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/testchat?autoReconnect=true&useSSL=false
  user: root
  password:
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true
